[package]
name = "hyprupdate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
git2 = "0.18.3"
gtk = "0.18.1"
toml = "0.8.12"
